#!/bin/bash
#BSUB -J ileal-combined_2022-01-19
#BSUB -P acc_untreatedIBD
#BSUB -W 144:00
#BSUB -q premium
#BSUB -n 2
#BSUB -M 8000
#BSUB -u christopher.tastad@mssm.edu
#BSUB -o output_%J.stdout
#BSUB -eo error_%J.stderr
#BSUB -L /bin/bash

# README
# This script should be executed at the site of the output dir

PROJ_DIR=/sc/arion/projects/untreatedIBD/kgettler/projects/cd-ileal/analysis/rnaseq			# project directory
NFC_PIPE=nf-core/rnaseq			# nf-core pipeline
NFC_VER=3.5			# nf-core pipeline version
NFC_PROFILE=singularity		# nf-core profile (singularity req'd on minerva)
SAMPLESHEET=ileal-combined_2022-01-19.csv
OUTDIR=ileal-combined_2022-01-19
GENOME=GRCh38				# reference genome

################################################################################

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

ml java
ml anaconda3
ml singularity

source $CONDA_PREFIX/etc/profile.d/conda.sh
conda init bash
conda activate nextflow

cd $PROJ_DIR 

nextflow run $NFC_PIPE \
	-r $NFC_VER \
	-profile $NFC_PROFILE \
	-w /sc/arion/scratch/$USER/2022-01-19/work \
	-c /sc/arion/projects/untreatedIBD/ctastad/projects/configs/conf/mssm.config \
	--input $SAMPLESHEET \
	--outdir $OUTDIR \
	--genome $GENOME \
	-resume

